ZSH=$HOME/dotfiles/oh-my-zsh

ZSH_THEME="tc"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
plugins=(git git-flow osx rvm tmux vagrant)

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh_aliases

export PATH="$HOME/Tools/git-deploy/bin:$HOME/Tools/reattach-to-user-namespace/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export EDITOR=vim
export TERM=xterm-256color

setopt extended_glob

# Tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Fast git completion
__git_files () { 
    _wanted files expl 'local files' _files     
}

# rbenv
eval "$(rbenv init -)"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# virtualenvwrapper
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
  source /usr/local/bin/virtualenvwrapper.sh
fi
if [ ! -d ~/Envs ]; then
  mkdir ~/Envs
fi
export WORKON_HOME=~/Envs
