ZSH=$HOME/dotfiles/oh-my-zsh

ZSH_THEME="tc"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
plugins=(git git-flow osx rvm tmux vagrant)

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh_aliases

export PATH="/usr/local/share/npm/bin:$HOME/bin:$HOME/projects/git-deploy/bin:$HOME/projects/cobuso/archive/scripts:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/Applications:$PATH"
export NODE_PATH="/usr/local/lib/node:$NODE_PATH"
export EDITOR=vim
export TERM=xterm-256color

setopt extended_glob

# RVM
[[ -s "/Users/tom/.rvm/scripts/rvm" ]] && source "/Users/tom/.rvm/scripts/rvm"  # This loads RVM into a shell session.

# Tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Fast git completion
__git_files () { 
    _wanted files expl 'local files' _files     
}

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
