source $HOME/.zsh_aliases

export PATH="$HOME/Tools/git-deploy/bin:$HOME/Tools/sesame.sh:$HOME/Tools/reattach-to-user-namespace/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export EDITOR=vim

setopt extended_glob

# Long history!
HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE

# Tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Fast git completion
__git_files () { 
    _wanted files expl 'local files' _files     
}

# virtualenvwrapper
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
  source /usr/local/bin/virtualenvwrapper.sh
fi
if [ ! -d ~/Envs ]; then
  mkdir ~/Envs
fi
export WORKON_HOME=~/Envs

# tmuxinator completion
source ~/Dotfiles/zsh/completion/tmuxinator.zsh
export DISABLE_AUTO_TITLE=true